name: expense_tracker
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get: ^4.6.5
  curved_navigation_bar: ^1.0.3
  toggle_switch: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_slidable: ^3.0.0
  image_picker: ^1.0.4
  syncfusion_flutter_datepicker: ^23.1.43
  flutter_local_notifications: ^16.1.0
  fluttertoast: ^8.2.4
  money_formatter: ^0.0.5
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  rxdart: ^0.27.7
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/budget.png"

flutter:


  uses-material-design: true

  assets:
    - images/expense-logo.png
    - images/user-logo.png
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
